### ISSUE TITLE
Sourcing the auditor pubkey

### ISSUE THREAD

**Issue by sanjit-bhat** [cloudflare/plexi#13]
As far as I can tell, the [auditor_config function](https://github.com/cloudflare/plexi/blob/9d0a0779d7c4fb1facfaf4905957e158f9ce66ee/plexi_core/src/client/mod.rs#L95) reads the auditor pubkey from [this cloudflare page](https://plexi.key-transparency.cloudflare.com/info) when the main [audit function](https://github.com/cloudflare/plexi/blob/9d0a0779d7c4fb1facfaf4905957e158f9ce66ee/plexi_cli/src/cmd.rs#L191) tries to audit a different cloudflare page that has signatures.

If so, this seems a bit circular? I'd think that plexi should get the auditor pubkey elsewhere, either baked into the source code or supplied by the user. (CC'ing @kevinlewi, since we talked about it during our meeting.)

**Comment by thibmeu** [comment]
the `auditor_config` function uses a base_url provided by the user/developer. For instance, with plexi_cli, this base url is provided via `--remote-url` or `PLEXI_REMOTE_URL` environment variable.

The user can pass their own verifying key via `--verifying-key` or `PLEXI_VERIFYING_KEY`.

This is meant to address the problem you're pointing out. If no verifying key is provided, that key is fetched from the auditor directory. For users that know the verifying key, they can set it as well.

If this does not correspond to the issue you're encountering, happy to have a chat.

**Comment by sanjit-bhat** [comment]
Ah, good these options exist! It'd be nice to spell out their interaction with auditor pubkeys in the README, since that's an important part of the transparency story.

For instance, the first time I used plexi, I didn't realize that the `remote-url` also provides the key. I just thought it pointed to the signatures. It'd also be nice to give an example that uses `verifying-key` in the README.

**Comment by thibmeu** [comment]
@sanjit-bhat readme update https://github.com/cloudflare/plexi/pull/14
